### ISSUE TITLE
resources/test broken with Firefox stable (59.0.1) on at least macOS

### ISSUE THREAD

**Issue by foolip** [w3c/web-platform-tests#10144]
As reported by @lukebjerring in https://github.com/w3c/web-platform-tests/pull/10100#issuecomment-375328006, resources/test is broken on master.

Confirmed on Mac after installing geckodriver from https://github.com/mozilla/geckodriver/releases

**Comment by foolip** [comment]
https://github.com/w3c/web-platform-tests/issues/10114 may be related, although it doesn't hang for me.

**Comment by foolip** [comment]
Actually on macOS there are failing tests going back as far as commit eb03407caedc4847867be415db35e1bba5bdb74b.

**Comment by foolip** [comment]
@jugglinmike, is there a quick way to reset the expectations to match the actual results?

**Comment by foolip** [comment]
Created https://github.com/w3c/web-platform-tests/pull/10145 to see what the failures are like when nothing has really changed.

**Comment by Hexcles** [comment]
So there are potentially two problems:

1. #10114 happens on some platforms, and has been fixed by me.
2. #10143 is the one that's most likely happening on Mac (and unfortunately isn't easy to fix).

Could you confirm you are seeing similar errors as in #10143? If yes, we can close this issue.

**Comment by foolip** [comment]
I actually installed geckodriver manually (per resources/test/README.md) so I don't think it's either of those issues.

However, now I do remember that I had to use Firefox Nightly on Linux last time I ran these tests, so it might be the same problem on macOS.

**Comment by foolip** [comment]
OK, the tests pass on macOS with `tox -- --binary=/Applications/FirefoxNightly.app/Contents/MacOS/firefox`.

When it failed I was using Firefox 58 and Firefox Nightly is 61. When I checked the Firefox stable version it updated itself to 59, but it still fails.

@jgraham, which version of Firefox is required for these tests?

**Comment by foolip** [comment]
My Linux workstation is busted and awaiting rescue, can someone else see if it currently work on Linux and with which Firefox versions?

**Comment by Hexcles** [comment]
@foolip we pretty much always use the cutting-edge geckodriver and Firefox Nightly, including this suite. If there's a mismatch of versions, geckodriver may complain and fail to connect (which might be what you saw).

I think I've actually fixed this very issue in #10116. `ci_resources_unittest.sh` should download Firefox Nightly to your HOME and pass the path to tox. But if you are directly using tox, you need to add that `--binary` argument yourself.

**Comment by foolip** [comment]
OK, so it's not the case that we expect Firefox N+ to always work, but rather that Firefox Nightly is the only one that will be kept working? In that case the documentation should say that nightly is required, and something should blow up if one tries running the tests with anything else. Would that make sense?

**Comment by jgraham** [comment]
Geckodriver is generally backwards compatible I think. @andreastt would know if there are exceptions to that.

There is another problem though; wptrunner sets an environment variable that causes gecko to crash on external network connections. Making this work requires setting a carefully curated set of prefs to disable all the Firefox features that try to connect to the network. We download the prefs file from mozilla-central but sometimes prefs change name, or features are removed, so what's in m-c isn't guaranteed to work for older Firefox versions. Therefore some changes will be required to make running tests with wptrunner reliable in older Firefox (this does not affect the resources tests though).

**Comment by Hexcles** [comment]
Sounds reasonable.

The expectation (and hopefully also the reality) is that if one uses `wpt run` (without extra arguments) or scripts like `ci_resources_unittest.sh`, Firefox Nightly is always downloaded and used by the scripts (otherwise we have a bug). The only chances one might use stable/older Firefox are: 1. use `wpt serve` and open the browser themselves; 2. explicitly pass the binary path to various tools. In both cases I think they should know what they are doing. @foolip WDYT?

**Comment by jgraham** [comment]
At present `wpt run firefox` with no extra arguments won't download a browser, although it will prefer a previously downloaded one if present.

We could change that, but it seems more surprising than using the one on `$PATH`. I would prefer a solution that worked for more Firefox versions e.g. downloading the correct prefs or making it possible to disable the crash-on-network feature.

**Comment by Hexcles** [comment]
No, but I've fixed `tools/ci/ci_resources_unittest.sh` to wire everything up correctly.  Use that to run the resource test suite.

If you prefer to run tox directly, you'd need to pass the binary path explicitly.

**Comment by foolip** [comment]
@Hexcles, do you think https://github.com/w3c/web-platform-tests/blob/master/resources/test/README.md should be updated to steer people towards the more well supported way of running the tests?

@lukebjerring, when you were trying to figure out how to run these tests, which documentation did you find and what did you end up trying first as a result?

**Comment by Hexcles** [comment]
I didn't actually know that file existed... Opened #10184.

BTW, on a second thought, `tools/ci/ci_resources_unittest.sh` isn't necessarily the "recommended" way, because it tries to install dependencies in ways that some users might not like, so I mention it as an "alternative" method instead.

**Comment by foolip** [comment]
Thanks @Hexcles, that's quite enough for me to not be confused next time I think.

**Comment by ahmadmiz** [comment]
Kiwait

**Comment by andreastt** [comment]
> Geckodriver is generally backwards compatible I think.

Which Firefox versions are compatible with geckodriver is [documented in the README](https://github.com/mozilla/geckodriver#supported-firefoxen).

At the time of writing, geckodriver supports Firefox 55 and greater. Certain WebDriver conformance fixes and bug fixes are only available in more recent Firefox versions. Because geckodriver is in a pre-release state we generally advise using it with Nightly, but it is known _to run_ with 55 and greater.

**Comment by gsnedders** [comment]
@jgraham wpt run isn't relevant here, because `resources/tests` doesn't use it, this is just using `webdriver.Firefox(firefox_binary=config.getoption("--binary"))`

**Comment by foolip** [comment]
> Because geckodriver is in a pre-release state we generally advise using it with Nightly

Oh, so there's something curious here I didn't pay attention to before: we're using marionette for wpt run, but geckodriver for these tests. Anyone know why? Is this our only dependency on geckodriver?

**Comment by gsnedders** [comment]
@foolip @lukebjerring We now also have #10652 about these failing, and I don't know how to tell if it's a dupe or not; do either of you know what was failing? https://github.com/w3c/web-platform-tests/pull/10100#issuecomment-375328006 doesn't link to any Travis run, and given there's no failing Travis run on that PR any more I don't know how to reasonably find it.

**Comment by gsnedders** [comment]
OK, so #10652 was a dupe, and this issue was fixed there.
