### ISSUE TITLE
Test-suite, Ahem font

### ISSUE THREAD

**Issue by gsnedders** [w3c/web-platform-tests#9105]
_From @tobireif on January 18, 2018 11:1_

I just was going through the test-suite, in three browsers, submitting results automatically and manually. Then I noticed ~"This test requires the Ahem font to be installed" - thus probably many test results were false.

Would it be possible to @font-face the Ahem font? (Everywhere, or for each test that requires it).

Then testing won't go wrong as it just did.

_Copied from original issue: w3c/csswg-drafts#2200_

**Comment by gsnedders** [comment]
FWIW, this would be better discussed on the w3c/web-platform-tests repository.

This has been discussed on several occasions before [citation needed], but I think we've always decided that it's simply too much effort to go through and add `@font-face` to every test case that uses it.

**Comment by gsnedders** [comment]
_From @frivoal on January 19, 2018 2:7_

@gsnedders That's understating it: the current policy is actually not to add `@font-face` for Ahem in new tests. I'd be happy to change that, but that's what it is for now, IIUC.

**Comment by gsnedders** [comment]
_From @liamquin on January 19, 2018 2:50_

On Fri, 2018-01-19 at 01:00 +0000, Geoffrey Sneddon wrote:
> 
> [...] I think we've always decided that it's simply too much effort
> to go through and add `@font-face` to every test case that uses it.

Isn't there a move for browsers to ignore installed fonts and use only
embedded plus serif/sans/mono/fantasai/cursive or whatever the list is?

What if the test harness JavaScript code injected @font-face for Ahem
to every test??

CSS never did have a way to distinguish two fonts of the same name but
from different foundries (there's a sans-serif text face called Symbol,
for example, which is not at all the same as Adobe Symbol), nor to
request a specific-or-later version of a font, but i'm not aware of any
other fonts called "ahem", so the only problem is not having installed
the font, not getting the wrong font.


-- 
Liam Quin, W3C, http://www.w3.org/People/Quin/
Staff contact for Verifiable Claims WG, SVG WG, XQuery WG

Web slave for http://www.fromoldbooks.org/

**Comment by gsnedders** [comment]
_From @tobireif on January 19, 2018 9:38_

> FWIW, this would be better discussed on the w3c/web-platform-tests repository.

Thanks for the info, next I'll try to remember to submit any issues there.

> the current policy is actually not to add @font-face for Ahem

I'd prefer it if no test would require any specific font. But when a test writer has good reasons to require a specific font, then that font should be right there, without requiring the test-suite user to do anything regarding any required assets (fonts, images etc). @font-face is a great way to load the required font. When I supply test cases for issue reports I can't require the visitor to install the required font, so I make sure it's right there using @font-face, eg:

https://bugs.chromium.org/p/chromium/issues/detail?id=800693
->
https://tobireif.com/non_site_stuff/test_case_for_font_position_report/

I ran the CSS Grid test-suite, and I inadvertently supplied potentially-incorrect test results because the tests that require a specific font don't @font-face it. The note I then saw at a later point in time is not sufficient: I already had submitted hundreds of results (running the suite in 3 browsers) before I saw the note telling me to install a font on my machine, as if we are still in a time where @font-face didn't exist 😀

You can @font-face any respective required font(s) where necessary (or eg make sure that no existing or future test requires any fonts) - or you'll probably get even more incorrect test results by people who want to contribute by running the test suite, but aren't familiar with the implicit requirements that are only obvious among test-suite contributors, WG members, etc.

By the way, I'd be quite busy if every site required me to install a font, so I don't do that 😀 Supplying the font using @font-face is easy for future tests, and perhaps a script could ensure it for the existing ones. Or eg
> the test harness JavaScript code [could] inject[...] @font-face for Ahem to every test[...]

**Comment by csnardi** [comment]
Leaving this just as an offhand comment: using Ahem but forcing users to install it results in failures even on wpt.fyi; see https://github.com/w3c/wptdashboard/issues/218.

**Comment by jgraham** [comment]
`--install-fonts` is supposed to work with wptrunner (i.e. `wpt run`) to avoid having to install it. I know there are some issues on Windows and maybe OSX because it didn't trivially fix the problem on Mozilla's CI, but it's something we're working towards solving.

**Comment by csnardi** [comment]
The failures I was referring to are on Sauce; wptrunner installs the fonts on the local machine but not on the Sauce VM. As I mentioned in the above issue, this should be a fairly simple fix with Sauce prerun scripts, but I just wanted to bring that up as point.

**Comment by tobireif** [comment]
Just to be clear: This is the test suite I was running (in three browsers):

http://test.csswg.org/harness/suite/css-grid-1_dev

And this report here is about the issue where tests in the above suite require the Ahem font but don't @font-face it.

**Comment by tabatkins** [comment]
> Isn't there a move for browsers to ignore installed fonts and use only
> embedded plus serif/sans/mono/fantasai/cursive or whatever the list is?

This is an important sub-point - in an attempt to reduce fingerprinting surface, Firefox at least is considering turning off the ability to reference installed fonts at all - all you have access to are the generic fonts and @font-face.  Relying on Ahem being locally installed would obviously be incompatible with this.

**Comment by jgraham** [comment]
Yes, obviously if browsers stop supporting system fonts we'll need to update all the tests to supply Ahem as a webfont. But I doubt that such a sweeping change will happen until that actually ships, given the difficulties of landing any changes to CSS tests. In the meantime it makes sense to improve the infra so that Ahem is available where possible.

**Comment by tobireif** [comment]
> Yes, obviously if browsers stop supporting system fonts we'll need to update all the tests to supply Ahem as a webfont. 

Making sure that any required assets (fonts, images, etc) are present is already necessary, for the reasons I described above. I had submitted tens or hundreds of potentially incorrect test results because the required font was not supplied.

Requiring the test-suite user to install a font is not necessary since @font-face is widely supported.

>  it makes sense to improve the infra so that Ahem is available where possible.

If every existing and future browser-based test (in every test-suite) which requires a font references it via @font-face, the issue is solved for all browser-based tests, right? (the @font-face rule could get injected dynamically)

**Comment by frivoal** [comment]
Legacy tests are one thing. But new tests are another. I still do not understand why we discourage (as it: ask for it to be removed during code review) loading Ahem with `@font-face` in code reviews.

**Comment by tobireif** [comment]
> Legacy tests are one thing. But new tests are another. 

It would be great if both categories could get fixed 😁

I'd gladly run the Grid test-suite again, and it would work out-of-the-box for every other new tester as well.

> I still do not understand why we discourage (as it: ask for it to be removed during code review) loading Ahem with @font-face in code reviews.

Seems strange to me as well. It's a great option for making sure that the required asset gets loaded . Adding @font-face lines is as normal and easy and OK as referencing an image using img src.

**Comment by jgraham** [comment]
So I certainly agree that getting people to use `@font-face` for new tests is a good idea.

For legacy tests I don't have any objection,  but I think what's requried is someone to do the work of updating all the tests and getting the change through code review. If you want to see this happen, I encourage you to be that person :) In the meantime we should also fix up the infrastructure to support installing Ahem.

**Comment by tobireif** [comment]
> So I certainly agree that getting people to use @font-face for new tests is a good idea.

Sounds good to me!

> For legacy tests I don't have any objection, but I think what's requried is someone to do the work of updating all the tests and getting the change through code review. If you want to see this happen, I encourage you to be that person :)

Unfortunately, time doesn't allow me to fix the existing W3C web platform tests where the test author hadn't referenced required assets.

By the way, I don't think it would need to be done manually: a script could go through the files and add the lines for each test (or ideally just for each test that requires a font).

**Comment by gsnedders** [comment]
Do we want to require people using `@font-face` to include `local`? IIRC, someone had perf concerns about loading Ahem over the network for thousands of tests (though surely it's not really much worse than testharness.js, esp. with caching). If so, how do we lint for that? (I doubt we can do it well enough without parsing CSS…)

Do we want to lint that tests using Ahem include `@font-face`?

**Comment by tobireif** [comment]
> Do we want to require people using @font-face to include local?

If you mean that the @font-face would ref the font in a local dir - I think that nobody should be required to have anything locally. All the Ahem @font-face rules should point to the same location on the server.

> IIRC, someone had perf concerns about loading Ahem over the network for thousands of tests (though surely it's not really much worse than testharness.js, esp. with caching).

Yep, I think that caching solves that issue.

**Comment by gsnedders** [comment]
>If you mean that the @font-face would ref the font in a local dir - I think that nobody should be required to have anything locally. All the Ahem @font-face rules should point to the same location on the server.

I meant requiring something like

```
@font-face {
 font-family: Ahem;
 src: local(Ahem), url(/fonts/Ahem.ttf);
}
```

which doesn't require it locally at all, but also avoids having to load it over the network if it exists locally, given whomever's concern about performance.

**Comment by tobireif** [comment]
Sure, as long as the font loads on machines where it's not installed locally it's fine 😁

**Comment by liamquin** [comment]
On Tue, 2018-01-23 at 16:26 +0000, Geoffrey Sneddon wrote:
> > If you mean that the @font-face would ref the font in a local dir -
> > I think that nobody should be required to have anything locally.
> > All the Ahem @font-face rules should point to the same location on
> > the server.
> 
> I meant requiring something like
> 
> ```
> @font-face {
>  font-family: Ahem;
>  src: local(Ahem), url(/fonts/Ahem.ttf);
> }

Unfortunately there's no way to know you're getting the right Ahem font
- there's no support for something like
   font-vendor: "CSS WG";
   font-version-min: 1.03;
so someone who downloaded the Ahem font a decade ago will get their
version, and if anyone else makes, say, a Google font called Ahem, all
Ahem will break loose.

The font is 22KBytes uncompressed, 4205 bytes gzip'd, and given that
most people running the tests will presumably run more than one and
that HTTP 1.1 doesn't even require a separate connection to check it'll
be cached, probably better to have local("Ahem") only as a fallback.


-- 
Liam Quin, W3C, http://www.w3.org/People/Quin/
Staff contact for Verifiable Claims WG, SVG WG, XQuery WG

Web slave for http://www.fromoldbooks.org/

**Comment by jgraham** [comment]
I don't think we shoud worry about unattributed performance concerns at all, or attributed ones that aren't backed up with data.

The problem here — and I think it is the only problem — is simply figuring out how to land such a change given the general change-adverse culture of CSSWG.

**Comment by gsnedders** [comment]
@jgraham In this case I'm pretty sure the answer is ask for forgiveness and not permission. There are very few ways in which it is potentially worse (most notably I think dealing with implementations that don't support TTF fonts).

**Comment by frivoal** [comment]
> The problem here — and I think it is the only problem — is simply figuring out how to land such a change given the general change-adverse culture of CSSWG.

The change-adverse culture of the CSSWG is mostly about dislikeing removal of previously available information.

This does no such thing, and I don't see why anybody would complain.

As far as my memory goes (and it may be failing), @gsnedders is the one who was telling me not to include `@font-face` rules for Ahem.

> There are very few ways in which it is potentially worse (most notably I think dealing with implementations that don't support TTF fonts).

Are there any such things outside of historical implementations?

Even if that's the case, putting `local("Ahem")` as a fallback seems it would solve it, and have no downside for everyone else.

**Comment by tobireif** [comment]
(re TTF: WOFF might be the most-widely supported web font format) (plus WOFF2 for perf)

**Comment by jgraham** [comment]
FWIW, I think if there's support for doing this, someone will review the change, and we aren't going to get bogged down in edge cases, or told that the WG have to have a F2F discussion that blocks landing the change, it might be worth upping the priority here. It would solve a real problem in that the current code we have to install the fonts is somewhat invasive (since it changes system configuration) and doesn't seem to work in all cases (I have seen it break on Windows < 10 and on OSX for no obvious reason). So it could be worthwhile figuring out how this could be put on the roadmap.

**Comment by frivoal** [comment]
I suggest agreeing on a standard way to embed Ahem first, then making a lint and an update to the documentation, to make sure the problem stops getting worse, then sending one (or more) PR per spec. 1 PR for the whole of CSS is unlikely to get anyone to review it.

**Comment by gsnedders** [comment]
@frivoal I suspect nobody will review such a huge change even if split up; realistically I think the sane way to land it is just to check it doesn't change results (or even writing custom code and checking it doesn't change any screenshot).

**Comment by frivoal** [comment]
I will review it for the specs I edit. That's not enough, for every spec, but "nobody will do it" is not true :)

As for checking that it doesn't change results or doesn't change screenshots, that's great of automated tests, but we (unfortunately) also have quite a few tests which are not.

Maybe we can automatically validate that all the reftests and visual tests and testsharness tests are updated correctly, and land that in 1 pull request, and have per spec pull requests for the rest.

That means the number of tests that need to be reviewed manually is much smaller, some of these pull requests will be reviewed by their spec's editor. Sure that won't cover everything, and many you'll end up being the one looking at leftovers. But these will be much smaller leftovers.
